name: SSH via tmate (Fixed)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Запуск tmate сессии с принудительным доступом
      uses: mxschmitt/action-tmate@v3
      with:
        # Это заставит GitHub Actions авторизовать именно ваш аккаунт без проверки локальных SSH ключей
        limit-access-to-actor: true
